POST http://localhost:3003/api/blogs
Content-Type: application/json

{ 
    "title": "Soda Lovers",
    "author": "Koka Colah", 
    "url": "www.pepsiisthedevil.com", 
    "likes": "3",
    "userId": "60abe68ae5019e1a86b613f2"
}